### ISSUE TITLE
API Re-factor

### ISSUE THREAD

**Issue by evaneus** [PieLabs/pie-project#51]
cross cutting issue for some decisions made on API:

- remove `elementModels` function 
- remove `register-pie` listener and `register-pie` event (use whenDefined instead)
- remove `reset` and `resetResponse` - will move these out to a utility  function`reset(sessions):sessions
- rename `response-changed` to `session-changed`

# Libraries @ version
* [x] pie-player @ 3.0.0
* [x] pie-catalog-client @ 1.0.0
* [x] pie-support-base (merge feature/api-change to master)
* [x] pie-cli @ 8.0.0
* [x] corespring-choice @ ???
* [ ] corespring-number-line @ ????
* [ ] corespring-placement-ordering @ ???
* [ ] corespring-match @ ???
* [ ] pie-with-toolbar-demo - try w/ regular custom elements w/ model/session

**Comment by edeustace** [comment]
need to prove that rm-ing register-pie will be ok
